project:
  type: website
  output-dir: docs
filters:
  - pandoc-ext/diagram
markdown_extensions:
  - md_in_html  
website:
  title: DRN Group
  reader-mode: true
  search: 
    location: navbar
    type: overlay
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - text: Guides
        menu:
        - href: C0DFT/home_DFT.qmd
          text: DFT Tutorials
      - href: publications.qmd
        text: Publications
      - href: people.qmd
        text: People
      - href: about.qmd
        text: About
  sidebar:
    style: floating
    search: true
    logo: _figs/logo.png
    logo-alt: Mysteries of physics, mathematics, and life
    contents:
      - section: "Resources"
        contents:
          - href: C0resources/QE/QE.qmd
            text: Espresso
      - text: "About"
        href: "about.qmd"
format:
  html:
    toc: true
    code-fold: true
    execute:
      enabled: true
    theme: [css/style.scss]
    css: [css/buttons.css, 
          css/tabs.css,
          css/callouts.css,
          css/fonts-ebgaramond.css, 
          css/fonts-hand.css, 
          css/shapes.css, 
          css/leaders.css]
    include-in-header:
      - file: scripts/scripts.js
      - file: scripts/leader-line-master/my-lines.js
      - file: scripts/leader-line-master/leader-line-flowchart.js
    include-after-body: 
      - text: |
          <script src="/scripts/leader-line-master/leader-line.min.js"></script> 

